export const categories = [
  { id: "all", label: "All work" },
  { id: "social-media", label: "Social-media campaign" },
  { id: "packaging", label: "Packaging" },
  { id: "editorial", label: "Editorial spread" },
  { id: "fashion", label: "Fashion campaign" },
  { id: "product", label: "Product visualization" },
  { id: "poster", label: "Poster" },
  { id: "photo-manipulation", label: "Photo manipulation" },
  { id: "food", label: "Food advertisement" },
  { id: "sports", label: "Sports campaign" },
  { id: "web", label: "Web / key visual" },
  { id: "ai-avatars", label: "AI avatars & imagery" },
] as const;

export type CategoryId = (typeof categories)[number]["id"];

export type Project = {
  slug: string;
  title: string;
  category: Exclude<CategoryId, "all">;
  categoryLabel: string;
  year: string;
  cover: string;
  summary: string;
  concept: string;
  services: string[];
  tags: string[];
  gallery: string[];
  orientation?: "portrait" | "landscape" | "square";
  featured?: boolean;
  accent?: string;
};

export const projects: Project[] = [
  {
    slug: "creative-network-strategy",
    title: "Creative Network",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/creative-network.webp",
    summary: "A crisp agency poster that turns digital-growth strategy into an approachable, conversion-focused visual.",
    concept: "Structured typography, coral accents and overlapping circular frames balance a professional agency message with a warm, human working scene. The result keeps a dense service offer clear at a glance.",
    services: ["Poster design", "Advertising layout", "Typography", "AI-assisted imagery"],
    tags: ["Poster", "Agency", "Social media"],
    gallery: ["/work/posters/creative-network.webp"],
    orientation: "portrait",
    accent: "#ff5b4d",
  },
  {
    slug: "coco-beauty-bar",
    title: "Coco Beauty Bar",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/coco-beauty-bar.webp",
    summary: "A refined salon-services poster pairing blush tones, deep charcoal and gold detailing with an elegant editorial portrait.",
    concept: "Soft curves and metallic-style borders frame the client experience while a carefully spaced service list keeps the information practical. The palette and serif typography position the salon as polished and premium.",
    services: ["Poster design", "Beauty art direction", "Information hierarchy", "AI-assisted imagery"],
    tags: ["Poster", "Beauty", "Luxury"],
    gallery: ["/work/posters/coco-beauty-bar.webp"],
    orientation: "portrait",
    accent: "#e9b9b8",
  },
  {
    slug: "fitness-park-racine",
    title: "Fitness Park Racine",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/fitness-park-racine.webp",
    summary: "A high-energy fitness poster built around bold scale, electric lime and a focused athlete portrait.",
    concept: "Oversized condensed messaging and sharp diagonal forms create forward motion, while the restrained black, white and lime palette makes the offer immediately recognizable across print and social placements.",
    services: ["Poster design", "Sports art direction", "Campaign typography", "AI-assisted imagery"],
    tags: ["Poster", "Fitness", "Campaign"],
    gallery: ["/work/posters/fitness-park-racine.webp"],
    orientation: "portrait",
    accent: "#b4e000",
  },
  {
    slug: "atlantic-clinic-casablanca",
    title: "Atlantic Clinic",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/atlantic-clinic.webp",
    summary: "A reassuring healthcare poster combining a clean clinical palette with accessible service and emergency information.",
    concept: "A calm blue-to-teal system, generous white space and soft circular geometry create trust without feeling cold. The doctor portrait anchors the message while icons make essential services easy to scan.",
    services: ["Poster design", "Healthcare communication", "Icon system", "AI-assisted imagery"],
    tags: ["Poster", "Healthcare", "Information design"],
    gallery: ["/work/posters/atlantic-clinic.webp"],
    orientation: "portrait",
    accent: "#45aeb3",
  },
  {
    slug: "slayz-fashion-store",
    title: "Slay'z Fashion",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/slayz-fashion.webp",
    summary: "A streetwear retail poster with oversized type, elevated styling and a confident burgundy-and-sand palette.",
    concept: "Monumental lettering becomes part of the set, giving the campaign an editorial scale while dark stepped plinths frame the cast. The composition connects fashion attitude with a direct retail call to action.",
    services: ["Poster design", "Fashion art direction", "Campaign layout", "AI-assisted imagery"],
    tags: ["Poster", "Fashion", "Streetwear"],
    gallery: ["/work/posters/slayz-fashion.webp"],
    orientation: "portrait",
    accent: "#6d1421",
  },
  {
    slug: "sovoycars-rental",
    title: "Sovoycars Rental",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/sovoycars-rental.webp",
    summary: "A digital-first car-rental poster that visualizes a smooth airport booking journey through layered interface cards.",
    concept: "Navy and orange establish a clear service identity while floating booking, support and route modules explain the customer journey without turning the poster into a manual. The central portrait adds confidence and hospitality.",
    services: ["Poster design", "Interface visualization", "Advertising layout", "AI-assisted imagery"],
    tags: ["Poster", "Automotive", "Digital service"],
    gallery: ["/work/posters/sovoycars-rental.webp"],
    orientation: "portrait",
    accent: "#f26300",
  },
  {
    slug: "moods-cafe-restaurant",
    title: "Moods Café",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/moods-cafe.webp",
    summary: "A warm lifestyle poster for an all-day café, mixing editorial type with relaxed Mediterranean color and texture.",
    concept: "The campaign uses oversized background lettering, hand-drawn curves and a soft paper finish to create a tactile, leisurely mood. The dining portrait and concise daypart menu make the offer feel aspirational and immediate.",
    services: ["Poster design", "Hospitality art direction", "Editorial typography", "AI-assisted imagery"],
    tags: ["Poster", "Hospitality", "Food"],
    gallery: ["/work/posters/moods-cafe.webp"],
    orientation: "portrait",
    accent: "#c95e31",
  },
  {
    slug: "sun-brokers-agency",
    title: "Sun Brokers Agency",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/sun-brokers.webp",
    summary: "A confident real-estate poster that presents a full property service offer with premium green-and-gold branding.",
    concept: "Curved architectural framing connects the agent portrait to the property context, while modular icon rows make five services readable in seconds. Deep green and warm metallic tones communicate trust and local expertise.",
    services: ["Poster design", "Real-estate branding", "Information design", "AI-assisted imagery"],
    tags: ["Poster", "Real estate", "Branding"],
    gallery: ["/work/posters/sun-brokers.webp"],
    orientation: "portrait",
    accent: "#c8873d",
  },
  {
    slug: "le-cinq-edit",
    title: "Le Cinq Edit",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/posters/le-cinq-edit.webp",
    summary: "A vintage-fashion collage poster built from torn-paper edges, editorial portraits and richly textured accessories.",
    concept: "A central typographic panel creates order inside a dense image collage. Burgundy, olive and warm paper tones unite multiple fashion moments into a curated boutique story with the character of a printed lookbook.",
    services: ["Poster design", "Fashion collage", "Editorial art direction", "AI-assisted imagery"],
    tags: ["Poster", "Vintage fashion", "Collage"],
    gallery: ["/work/posters/le-cinq-edit.webp"],
    orientation: "portrait",
    accent: "#67151c",
  },
  {
    slug: "own-your-zone",
    title: "Own Your Zone",
    category: "social-media",
    categoryLabel: "Social-media campaign",
    year: "2026",
    cover: "/work/velocity-run.webp",
    summary: "A kinetic launch system for a fictional performance sneaker, built for feed-first storytelling.",
    concept: "The campaign turns product energy into a modular social system: hero posts, launch beats, athlete moments and bold performance typography that can scale from a square post to a full campaign takeover.",
    services: ["Campaign art direction", "Social design system", "AI-assisted imagery", "Typography"],
    tags: ["Campaign", "Social", "Sports"],
    gallery: ["/work/velocity-run.webp", "/work/velocity-product.webp", "/work/red-shift.webp"],
    featured: true,
    accent: "#f1c40f",
  },
  {
    slug: "night-objects",
    title: "Night Objects",
    category: "packaging",
    categoryLabel: "Packaging",
    year: "2026",
    cover: "/work/maison-elise.webp",
    summary: "Luxury fragrance and beauty packaging studies with tactile materials, premium lighting and editorial restraint.",
    concept: "A packaging-focused exploration of glass, paper, foil, stone and light. The visual language shifts between classic French luxury and contemporary cosmetic minimalism while keeping the product as the hero.",
    services: ["Packaging direction", "Product styling", "Key visual", "AI visualization"],
    tags: ["Packaging", "Beauty", "Luxury"],
    gallery: ["/work/maison-elise.webp", "/work/hikari-dew.webp", "/work/nocturne-campaign.webp", "/work/ember-skin.webp"],
    featured: true,
    accent: "#d4b47a",
  },
  {
    slug: "form-space",
    title: "Form / Space",
    category: "editorial",
    categoryLabel: "Editorial spread",
    year: "2026",
    cover: "/work/form-space.webp",
    summary: "A brutalist architecture editorial balancing monumental photography with disciplined typographic hierarchy.",
    concept: "The editorial system uses rigid grid logic, large display typography, asymmetry and carefully controlled white space. It is designed to feel credible as both a magazine cover and a longer publication system.",
    services: ["Editorial design", "Art direction", "Grid systems", "Typography"],
    tags: ["Editorial", "Architecture", "Print"],
    gallery: ["/work/form-space.webp", "/work/atelier-nord.webp", "/work/roast-theory.webp"],
    featured: true,
    accent: "#ff4b26",
  },
  {
    slug: "atelier-nord",
    title: "Atelier Nord",
    category: "fashion",
    categoryLabel: "Fashion campaign",
    year: "2026",
    cover: "/work/atelier-nord.webp",
    summary: "A clean northern fashion story expanded into cast imagery, couture studies and modern editorial styling.",
    concept: "This project explores fashion across multiple visual registers—from Swiss-inspired campaign design to couture casting and minimal studio portraits—while preserving a coherent sense of premium art direction.",
    services: ["Fashion art direction", "AI casting", "Editorial design", "Campaign imagery"],
    tags: ["Fashion", "Editorial", "AI"],
    gallery: ["/work/atelier-nord.webp", "/work/editorial-cast.webp", "/work/couture-looks.webp", "/work/couture-cast.webp"],
    featured: true,
    accent: "#1648ff",
  },
  {
    slug: "obsidian-fw",
    title: "Obsidian FW",
    category: "fashion",
    categoryLabel: "Fashion campaign",
    year: "2026",
    cover: "/work/obsidian-shadow.webp",
    summary: "Dark technical streetwear with tactile fabric details, campaign portraits and utilitarian styling.",
    concept: "A streetwear direction that leans into shadow, utility and technical detailing rather than luxury minimalism. The visual system is intentionally rougher, sharper and more tactical.",
    services: ["Streetwear direction", "Campaign graphics", "AI fashion imagery"],
    tags: ["Streetwear", "Campaign", "Fashion"],
    gallery: ["/work/obsidian-shadow.webp", "/work/obsidian-dark.webp", "/work/streetwear-cast.webp"],
    accent: "#d81d2a",
  },
  {
    slug: "sonic-grid-x1",
    title: "Sonic Grid X1",
    category: "product",
    categoryLabel: "Product visualization",
    year: "2026",
    cover: "/work/sonic-grid.webp",
    summary: "A technical consumer-electronics launch visual with product rendering, feature hierarchy and modular information design.",
    concept: "The product is treated as an engineered object rather than a lifestyle accessory. Blueprint cues, hard grids and electric blue create a clear technical identity while keeping the rendering premium.",
    services: ["Product visualization", "Launch key visual", "Information design", "AI rendering"],
    tags: ["Product", "Tech", "3D / AI"],
    gallery: ["/work/sonic-grid.webp", "/work/pulse-air.webp", "/work/aero-s9.webp"],
    featured: true,
    accent: "#154cff",
  },
  {
    slug: "chromaflux",
    title: "Chroma Flux",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/chroma-flux.webp",
    summary: "An acid club poster system using distortion, fluorescent contrast and intentionally aggressive typography.",
    concept: "A poster direction designed to feel tactile and imperfect. High-contrast halftone texture, stretched type and surreal portraiture create a graphic language that is far removed from the site's black-red identity.",
    services: ["Poster design", "Typography", "Experimental art direction"],
    tags: ["Poster", "Music", "Experimental"],
    gallery: ["/work/chroma-flux.webp", "/work/afterlight.webp", "/work/cala-sol.webp"],
    featured: true,
    accent: "#bbff00",
  },
  {
    slug: "beyond-real",
    title: "Beyond Real",
    category: "photo-manipulation",
    categoryLabel: "Photo manipulation",
    year: "2026",
    cover: "/work/stairway-clouds.webp",
    summary: "Surreal worlds, impossible environments and cinematic composites built to feel plausible enough to inhabit.",
    concept: "This collection focuses on scale, atmosphere and visual surprise. Each image uses a different genre—dreamscape, alien ecology, retro science fiction, fantasy and gothic portraiture—to demonstrate range.",
    services: ["Photo manipulation", "AI compositing", "Concept art", "Atmosphere design"],
    tags: ["Surreal", "Composite", "AI"],
    gallery: ["/work/stairway-clouds.webp", "/work/alien-valley.webp", "/work/retro-astronaut.webp", "/work/dragon-warrior.webp", "/work/gothic-baroness.webp"],
    featured: true,
    accent: "#7cc8ff",
  },
  {
    slug: "roast-theory",
    title: "Roast Theory",
    category: "food",
    categoryLabel: "Food advertisement",
    year: "2026",
    cover: "/work/roast-theory.webp",
    summary: "A tactile coffee campaign with collage, analogue print texture and product storytelling.",
    concept: "Instead of glossy food advertising, this project uses torn paper, halftone imagery and warm imperfect textures to communicate craft, origin and small-batch personality.",
    services: ["Food advertising", "Collage", "Packaging art direction", "Campaign design"],
    tags: ["Food", "Coffee", "Collage"],
    gallery: ["/work/roast-theory.webp", "/work/red-shift.webp"],
    featured: true,
    accent: "#b66f3a",
  },
  {
    slug: "built-to-fly",
    title: "Built to Fly",
    category: "sports",
    categoryLabel: "Sports campaign",
    year: "2026",
    cover: "/work/skyline-jump.webp",
    summary: "An explosive basketball performance campaign combining athlete action, product focus and hand-drawn energy.",
    concept: "A maximal sports language built around movement. Brush marks, handwritten accents, stats and product detail create a deliberately loud campaign that feels native to performance culture.",
    services: ["Sports campaign", "Key visual", "Athlete art direction", "Product advertising"],
    tags: ["Sports", "Advertising", "Sneakers"],
    gallery: ["/work/skyline-jump.webp", "/work/velocity-run.webp", "/work/velocity-product.webp"],
    accent: "#ffd31a",
  },
  {
    slug: "signal-interface",
    title: "Signal / Interface",
    category: "web",
    categoryLabel: "Web / key visual",
    year: "2026",
    cover: "/work/website-home.webp",
    summary: "Dark digital interfaces, campaign landing pages and key visuals built around strong information hierarchy.",
    concept: "A digital design study focused on dense portfolio interfaces and campaign pages. The work mixes modular panels, cinematic art direction, clear filtering and high-impact display type.",
    services: ["Web direction", "UI concept", "Key visual", "Interactive layout"],
    tags: ["Web", "UI", "Key visual"],
    gallery: ["/work/website-home.webp", "/work/website-archive.webp", "/work/website-case-study.webp", "/work/aero-s9.webp"],
    featured: true,
    accent: "#ff2424",
  },
  {
    slug: "persona-lab",
    title: "Persona Lab",
    category: "ai-avatars",
    categoryLabel: "AI avatars & imagery",
    year: "2026",
    cover: "/work/iridescent-avatar.webp",
    summary: "Fashion avatars, consistent personas, casting systems and character sheets designed for repeatable campaign use.",
    concept: "The focus is not a single AI portrait. It is character consistency: multiple angles, expressions, wardrobes and cast compositions that make fictional models usable across campaigns and content systems.",
    services: ["AI avatar creation", "Character consistency", "Fashion casting", "Character sheets"],
    tags: ["AI", "Avatars", "Fashion"],
    gallery: ["/work/iridescent-avatar.webp", "/work/lyra-sheet.webp", "/work/rowan-sheet.webp", "/work/lucien-sheet.webp", "/work/beauty-variations.webp", "/work/streetwear-cast.webp", "/work/rowan-portrait.webp"],
    featured: true,
    accent: "#b8d7ff",
  },
  {
    slug: "velours-nuit",
    title: "Velours Nuit",
    category: "packaging",
    categoryLabel: "Packaging",
    year: "2026",
    cover: "/work/nocturne-ad.webp",
    summary: "A darker fragrance campaign focused on dramatic product staging and nighttime luxury.",
    concept: "A second packaging direction that deliberately contrasts with soft cosmetic minimalism: dense blacks, luminous red edges, stone textures and premium glass rendering.",
    services: ["Packaging visualization", "Fragrance campaign", "Product rendering"],
    tags: ["Fragrance", "Packaging", "Luxury"],
    gallery: ["/work/nocturne-ad.webp", "/work/nocturne-campaign.webp", "/work/maison-elise.webp"],
    accent: "#a91520",
  },
  {
    slug: "cala-sol",
    title: "Cala Sol",
    category: "poster",
    categoryLabel: "Poster",
    year: "2026",
    cover: "/work/cala-sol.webp",
    summary: "A sunny mid-century travel poster inspired by classic tourism illustration and Mediterranean color.",
    concept: "This poster exists to prove the portfolio can leave dark tech aesthetics behind entirely. Flat illustrated shapes, warm paper texture and optimistic color build a nostalgic destination image.",
    services: ["Illustration", "Poster design", "Travel advertising"],
    tags: ["Poster", "Illustration", "Travel"],
    gallery: ["/work/cala-sol.webp"],
    accent: "#ef7659",
  },
  {
    slug: "aero-s9",
    title: "Aero S9",
    category: "product",
    categoryLabel: "Product visualization",
    year: "2026",
    cover: "/work/aero-s9.webp",
    summary: "A cool-toned automotive launch visual built around speed, reflection and electric performance.",
    concept: "The car is staged as a future object in motion. Silver surfaces, cyan light trails and a restrained data layer create a polished automotive key visual.",
    services: ["Automotive visualization", "Campaign key visual", "AI rendering"],
    tags: ["Automotive", "Product", "Campaign"],
    gallery: ["/work/aero-s9.webp", "/work/futuristic-autonomous-vehicle.webp"].filter(Boolean) as string[],
    accent: "#4edbff",
  },
];

// The autonomous vehicle image is optional in the data set; normalize any missing optional paths at render time.

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}

export function getRelatedProjects(project: Project, count = 4) {
  const sameCategory = projects.filter((item) => item.slug !== project.slug && item.category === project.category);
  const others = projects.filter((item) => item.slug !== project.slug && item.category !== project.category);
  return [...sameCategory, ...others].slice(0, count);
}
